import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "學習工具",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen w-full items-center bg-gray-400">
          <div className="bg-white w-full container flex flex-col  min-h-screen items-center">
            <Navbar />
            <div className="w-full p-4">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
